export const message = {
  "app.title": "React i18n Demo",
  "app.subtitle": "Demonstrating @i18n-toolkit/scanner",
  "navigation.home": "Home",
  "navigation.about": "About",
  "navigation.contact": "Contact",
  "auth.login": "Login",
  "auth.logout": "Logout",
  "common.loading": "Loading...",
  "common.success": "Success!",
  "common.error": "An error occurred",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "demo.title": "Demo Page",
  "demo.description": "This is a demo showcasing custom $LS function",
  "demo.switchLanguage": "Switch Language",
  "form.name": "Name",
  "form.email": "Email",
  "form.submit": "Submit"
};
