export const message = {
  "app.title": "React i18n Demo",
  "app.subtitle": "Demonstrating @i18n-toolkit/scanner",
  "navigation.home": "Home",
  "navigation.about": "About",
  "navigation.contact": "Contact",
  "auth.login": "Login",
  "auth.logout": "Logout",
  "common.loading": "Loading...",
  "common.success": "Success!",
  "common.error": "An error occurred",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "demo.title": "Demo Page",
  "demo.description": "This is a demo showcasing custom $LS function",
  "demo.switchLanguage": "Switch Language",
  "form.name": "Name",
  "form.email": "Email",
  "form.submit": "Submit",
  "test.comma": "Text with, comma",
  "test.quote": "Text with \"quotes\",\"包含\"引号\"的文本",
  "test.newline": "Text with\nNewline",
  "test.complex": "Complex: \"text",
  "special chars!\"": "复杂：\"文本\"，包含\n特殊字符！",
  "test.comma1": "Hello, world!",
  "test.comma2": "Welcome, dear user, to our amazing app!",
  "test.comma3": "Items: apple, banana, orange",
  "test.mixed": "Text with comma, and \"quotes\", and more!"
};
